name: Artikodin pull-request handler


on:
  # Runs on a pull request for the main branch
  pull_request:
    types:
      # Default events
      - opened
      - synchronize
      - reopened
      # But we also want to make sure a potential
      # exception request pull request is getting
      # closed if any was open
      - closed
    branch:
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false


jobs:
  handle_pr:
    name: Handle pull request

    runs-on: ubuntu-latest

    steps:
      - name: Synchronize authorization
        uses: suric-at/artikodin/request@main
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          target-repository: "${{ github.repository }}"
          target-pull-request: "${{ github.event.pull_request.number }}"
          target-git-sha: "${{ github.event.pull_request.head.sha }}"
          closing-pr: ${{ github.event.action == 'closed' }}

